package com.DietHelper;

import static com.DietHelper.Variables.*;

public class Examples {
    static void createExamplePatients() {
        Patient patient = new Patient();
        patient.setId(1);
        patient.setName("Arek");
        patient.setSurname("Kubek");
        patient.setGender(1);
        patient.setWeight(95);
        patient.setHeight(185);
        patient.setYear(1994);
        patient.setActivity(2);
        patient.calculateBmr();
        patient.calculateTotalMetabolism();

        Patient patient2 = new Patient();
        patient2.setId(2);
        patient2.setName("Paula");
        patient2.setSurname("Sedi");
        patient2.setGender(2);
        patient2.setWeight(55);
        patient2.setHeight(150);
        patient2.setYear(1995);
        patient2.setActivity(3);
        patient2.calculateBmr();
        patient2.calculateTotalMetabolism();

        patientList.add(patient);
        patientList.add(patient2);
        selectedPatient = 1;

        Product product = new Product();
        Product product2 = new Product();
        Product product3 = new Product();
        Product product4 = new Product();
        Product product5 = new Product();
        Product product6 = new Product();
        Product product7 = new Product();
        Product product8 = new Product();
        Product product9 = new Product();
        Product product10 = new Product();
        Product product11 = new Product();
        Product product12 = new Product();
        Product product13 = new Product();
        Product product14 = new Product();
        Product product15 = new Product();
        Product product16 = new Product();
        Product product17 = new Product();
        Product product18 = new Product();
        Product product19 = new Product();
        Product product20 = new Product();
        Product product21 = new Product();


        product.setName("Ryż");
        product.setProtein(7);
        product.setCarbohydrates(79);
        product.setFat(1);
        product.setCalories(354);
        product.setHasGluten(false);
        product.setVegetarian(true);
        product.setVegan(true);
        product.setHasLactose(false);
        product.setHasPeanuts(false);
        product.setForDiabetic(true);
        product2.setName("Kurczak");
        product2.setProtein(22);
        product2.setCarbohydrates(0);
        product2.setFat(1);
        product2.setCalories(100);
        product2.setHasGluten(false);
        product2.setVegetarian(false);
        product2.setVegan(false);
        product2.setHasLactose(false);
        product2.setHasPeanuts(false);
        product2.setForDiabetic(true);
        product3.setName("Wołowina");
        product3.setProtein(16);
        product3.setCarbohydrates(1);
        product3.setFat(16);
        product3.setCalories(209);
        product3.setHasGluten(false);
        product3.setVegetarian(false);
        product3.setVegan(false);
        product3.setHasLactose(false);
        product3.setHasPeanuts(false);
        product3.setForDiabetic(true);
        product4.setName("Mięso wieprzowe");
        product4.setProtein(14);
        product4.setCarbohydrates(1);
        product4.setFat(24);
        product4.setCalories(211);
        product4.setHasGluten(false);
        product4.setVegetarian(false);
        product4.setVegan(false);
        product4.setHasLactose(false);
        product4.setHasPeanuts(false);
        product4.setForDiabetic(true);
        product5.setName("Białko kfd");
        product5.setProtein(77);
        product5.setCarbohydrates(8);
        product5.setFat(5);
        product5.setCalories(387);
        product5.setHasGluten(false);
        product5.setVegetarian(true);
        product5.setVegan(false);
        product5.setHasLactose(true);
        product5.setHasPeanuts(false);
        product5.setForDiabetic(true);
        product6.setName("Tuńczyk");
        product6.setProtein(23);
        product6.setCarbohydrates(0);
        product6.setFat(0);
        product6.setCalories(95);
        product6.setHasGluten(false);
        product6.setVegetarian(true);
        product6.setVegan(false);
        product6.setHasLactose(false);
        product6.setHasPeanuts(false);
        product6.setForDiabetic(true);
        product7.setName("Płatki orkiszowe");
        product7.setProtein(11);
        product7.setCarbohydrates(63);
        product7.setFat(3);
        product7.setCalories(323);
        product7.setHasGluten(false);
        product7.setVegetarian(true);
        product7.setVegan(true);
        product7.setHasLactose(false);
        product7.setHasPeanuts(false);
        product7.setForDiabetic(true);
        product8.setName("Makaron");
        product8.setProtein(10);
        product8.setCarbohydrates(68);
        product8.setFat(2);
        product8.setCalories(340);
        product8.setHasGluten(true);
        product8.setVegetarian(true);
        product8.setVegan(true);
        product8.setHasLactose(false);
        product8.setHasPeanuts(false);
        product8.setForDiabetic(true);
        product9.setName("Mąka żytnia");
        product9.setProtein(8);
        product9.setCarbohydrates(74);
        product9.setFat(1);
        product9.setCalories(318);
        product9.setHasGluten(true);
        product9.setVegetarian(true);
        product9.setVegan(true);
        product9.setHasLactose(false);
        product9.setHasPeanuts(false);
        product9.setForDiabetic(true);
        product10.setName("Jaja");
        product10.setProtein(13);
        product10.setCarbohydrates(0);
        product10.setFat(11);
        product10.setCalories(155);
        product10.setHasGluten(false);
        product10.setVegetarian(true);
        product10.setVegan(false);
        product10.setHasLactose(false);
        product10.setHasPeanuts(false);
        product10.setForDiabetic(true);
        product11.setName("Dżem wiśniowy");
        product11.setProtein(0);
        product11.setCarbohydrates(38);
        product11.setFat(0);
        product11.setCalories(154);
        product11.setHasGluten(false);
        product11.setVegetarian(true);
        product11.setVegan(true);
        product11.setHasLactose(false);
        product11.setHasPeanuts(false);
        product11.setForDiabetic(false);
        product12.setName("Pomarańcza");
        product12.setProtein(1);
        product12.setCarbohydrates(12);
        product12.setFat(0);
        product12.setCalories(47);
        product12.setHasGluten(false);
        product12.setVegetarian(true);
        product12.setVegan(true);
        product12.setHasLactose(false);
        product12.setHasPeanuts(false);
        product12.setForDiabetic(true);
        product13.setName("Jabłko");
        product13.setProtein(0);
        product13.setCarbohydrates(14);
        product13.setFat(0);
        product13.setCalories(52);
        product13.setHasGluten(false);
        product13.setVegetarian(true);
        product13.setVegan(true);
        product13.setHasLactose(false);
        product13.setHasPeanuts(false);
        product13.setForDiabetic(true);
        product14.setName("Banan");
        product14.setProtein(3);
        product14.setCarbohydrates(51);
        product14.setFat(0);
        product14.setCalories(219);
        product14.setHasGluten(false);
        product14.setVegetarian(true);
        product14.setVegan(true);
        product14.setHasLactose(false);
        product14.setHasPeanuts(false);
        product14.setForDiabetic(false);
        product15.setName("Masło orzechowe kfd");
        product15.setProtein(26);
        product15.setCarbohydrates(16);
        product15.setFat(54);
        product15.setCalories(633);
        product15.setHasGluten(false);
        product15.setVegetarian(true);
        product15.setVegan(true);
        product15.setHasLactose(false);
        product15.setHasPeanuts(true);
        product15.setForDiabetic(true);
        product16.setName("Orzechy ziemne");
        product16.setProtein(25);
        product16.setCarbohydrates(13);
        product16.setFat(47);
        product16.setCalories(592);
        product16.setHasGluten(false);
        product16.setVegetarian(true);
        product16.setVegan(true);
        product16.setHasLactose(false);
        product16.setHasPeanuts(true);
        product16.setForDiabetic(true);
        product17.setName("Orzechy nerkowca");
        product17.setProtein(18);
        product17.setCarbohydrates(30);
        product17.setFat(44);
        product17.setCalories(553);
        product17.setHasGluten(false);
        product17.setVegetarian(true);
        product17.setVegan(true);
        product17.setHasLactose(false);
        product17.setHasPeanuts(true);
        product17.setForDiabetic(true);
        product18.setName("Warzywa na patelnie");
        product18.setProtein(2);
        product18.setCarbohydrates(7);
        product18.setFat(1);
        product18.setCalories(52);
        product18.setHasGluten(false);
        product18.setVegetarian(true);
        product18.setVegan(true);
        product18.setHasLactose(false);
        product18.setHasPeanuts(false);
        product18.setForDiabetic(true);
        product19.setName("Ser żółty gouda");
        product19.setProtein(24);
        product19.setCarbohydrates(2);
        product19.setFat(27);
        product19.setCalories(356);
        product19.setHasGluten(false);
        product19.setVegetarian(true);
        product19.setVegan(false);
        product19.setHasLactose(false);
        product19.setHasPeanuts(false);
        product19.setForDiabetic(true);
        product20.setName("Mozarella");
        product20.setProtein(18);
        product20.setCarbohydrates(2);
        product20.setFat(20);
        product20.setCalories(262);
        product20.setHasGluten(false);
        product20.setVegetarian(true);
        product20.setVegan(false);
        product20.setHasLactose(false);
        product20.setHasPeanuts(false);
        product20.setForDiabetic(true);
        product21.setName("Ser Tolonis półtłusty");
        product21.setProtein(13);
        product21.setCarbohydrates(8);
        product21.setFat(12);
        product21.setCalories(190);
        product21.setHasGluten(false);
        product21.setVegetarian(true);
        product21.setVegan(false);
        product21.setHasLactose(false);
        product21.setHasPeanuts(false);
        product21.setForDiabetic(true);


        productsList.add(product);
        productsList.add(product2);
        productsList.add(product);
        productsList.add(product2);
        productsList.add(product3);
        productsList.add(product4);
        productsList.add(product5);
        productsList.add(product6);
        productsList.add(product7);
        productsList.add(product8);
        productsList.add(product9);
        productsList.add(product10);
        productsList.add(product11);
        productsList.add(product12);
        productsList.add(product13);
        productsList.add(product14);
        productsList.add(product15);
        productsList.add(product16);
        productsList.add(product17);
        productsList.add(product18);
        productsList.add(product19);
        productsList.add(product20);
        productsList.add(product21);

        Meal meal = new Meal();


    }
}
